routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::match(['get','post'], '/', 'HomeController@index')->name('index');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/cashier', 'HomeController@cashier')->name('cashier');

Route::group(['prefix' => 'admin'], function () {
//    Voyager::routes();
    Route::resource('/concerts','ConcertController')->middleware('admin');
    Route::post('/concerts/store','ConcertController@store')->name('concert_create')->middleware('admin');
    Route::post('/concerts/destroy/{id}','ConcertController@destroy')->name('concert_destroy')->middleware('admin');
    Route::post('/concerts/update','ConcertController@update')->name('concert_update')->middleware('admin');
    Route::resource('cities','CityController')->middleware('admin');
    Route::post('/cities/store','CityController@store')->name('city_store')->middleware('admin');
    Route::post('/cities/destroy/{id}','CityController@destroy')->name('city_destroy')->middleware('admin');
    Route::post('/cities/update','CityController@update')->name('city_update')->middleware('admin');
    Route::resource('addresses','AddressController')->middleware('admin');
    Route::post('/addresses/update','AddressController@update')->name('address_update')->middleware('admin');
    Route::post('/addresses/store','AddressController@store')->name('address_store')->middleware('admin');
    Route::post('/addresses/destroy/{id}','AddressController@destroy')->name('address_destroy')->middleware('admin');
    Route::get('/files','FileController@files')->name('files')->middleware('admin');
    Route::get('/payments','PaymentController@payments')->name('payments')->middleware('admin');
    Route::get('/users/create','AdminController@create_user')->name('users_create')->middleware('admin');
    Route::post('/users/store','AdminController@store_user')->name('users_store')->middleware('admin');
//    Route::get('/users/edit/{id}','AdminController@edit_user')->name('users_edit')->middleware('admin');
    Route::post('/users/update','AdminController@update_user')->name('users_update')->middleware('admin');
    Route::post('/users/destroy/{id}','AdminController@destroy_user')->name('users_destroy')->middleware('admin');
    Route::get('/users','AdminController@users')->name('users')->middleware('admin');

});

Route::get('/create_eticket','ETicketController@create')->name('create')->middleware('admin');
Route::post('/store_eticket','ETicketController@store')->name('store_ticket')->middleware('admin');
Route::get('edit_eticket/{id}','ETicketController@edit')->name('ticket_edit')->middleware('admin');
Route::put('update_eticket/{id}','ETicketController@update')->name('ticket_update')->middleware('admin');
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);

    return redirect()->back();
})->name('locale');



Route::get('prices/{id}', 'ConcertController@prices')->name('prices');
Route::post('savePlaces', 'ConcertController@savePlaces')->name('savePlaces');
Route::post('getPlaces', 'ConcertController@getPlaces')->name('getPlaces');

Route::post('removeColor', 'ConcertController@removeColor')->name('removeColor');
Route::post('/removeTicket', 'CartController@removeTicket')->name('removeTicket');

Route::post('reservePlace', 'CartController@reservePlace')->name('reservePlace');
Route::post('clearCart', 'CartController@clearCart')->name('clearCart');
Route::post('processingStatus','CartController@status')->name('processingStatus');

Route::get('calculations/{id}', 'HomeController@calculations')->name('calculations');
Route::get('statistics/{id}', 'HomeController@statistics')->name('statistics');
Route::get('sales/{id}', 'HomeController@sales')->name('sales');
Route::get('report/{id}', 'HomeController@report')->name('report');
Route::get('scene/{id}', 'ConcertScene@order_ticket')->name('order-ticket');
//Route::get('ticket', 'HomeController@ticket')->name('ticket');

Route::get('ticket','ETicketController@index')->name('tickets');
Route::get('concert/{id}', 'HomeController@concert_id')->name('concert-id');

// Payment
//Route::get('checkout/{id}','CheckoutController@index')->name('checkout_id');
Route::get('invoice/{id}','CheckoutController@index')->name('invoice');
Route::match(['get','post'], '/checkout','CheckoutController@checkout')->name('checkout');
Route::post('payment','CheckoutController@payment')->name('payment');
//

Route::get('about','HomeController@about')->name('about');
Route::get('contacts','HomeController@contacts')->name('contacts');



//Route::get('/admin','AdminController@index')->name('admin');
//Route::get('dnk/admin','AdminController@login')->name('dnk_admin');

Route::get('/admin/orders','AdminController@orders')->name('orders')->middleware('admin');

app/Concert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Concert extends Model
{
    protected $fillable = [
        'name', 'date','image','status','ticket_order','canceled','codes_without_d','no_in_shop','hide_concert','another_codes','pay_for_organizator',
        'places','archive','description','before','after','hours','minutes','dk_id', 'city_id', 'organizer_id'
    ];

    public $timestamps = false;

//    public function prices() {
//        return $this->hasMany(ConcertPrices::class);
//    }

    public function places() {
        return $this->hasMany(Places::class, 'concert_id', 'id');
    }

    public function colors() {
        return $this->hasMany(Colors::class)->orderByDesc('price');
    }

    public function cultures() {
        return $this->belongsTo(Culture::class, 'dk_id', 'id');
    }

    public function cities() {
        return $this->belongsTo(City::class, 'city_id', 'id');
    }

    public function organizers() {
        return $this->belongsTo(Organizators::class, 'organizer_id', 'id');
    }


//    public function concert_prices()
//    {
//        return $this->hasManyThrough(
//            ConcertPrices::class, Places::class,
//            'concert_id', 'place_id', 'id', 'id');
//    }

}

app/Http/Controllers/ConcertController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\Color;
use App\Colors;
use App\Concert;
use App\ConcertPrices;
use App\Culture;
use App\Helper\Cart;
use App\Helper\ColorsHelper;
use App\Helper\Helper;
use App\Organizators;
use App\Places;
use App\Sections;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ConcertController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organizers = Organizators::all();
        $cultures = Culture::all();
        $concerts = Concert::all();
        $cities = City::all();
        return view('concerts.index', [
            'organizers' => $organizers,
            'cultures' => $cultures,
            'concerts' => $concerts,
            'cities' => $cities
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
//    public function create(Request $request)
//    {
////        $colors = Color::orderBy('id', 'desc')->get();
//        $dk = Culture::get();
//        return response()->json(['dk' => $dk]);
//    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'culture' => 'required',
            'name' => 'required',
            'organizer' => 'required',
            'date' => 'required',
            'city' => 'required',
            'description' => 'required',
            'ticket_order' => 'required',
            'hours' => 'required',
            'minutes' => 'required',
            'image' => 'required'
        ]);


        $image = $request->file('image');
        if ($image && isset($image)) {
            $file = $image->store('imagesGoods', 'public');
            $name = basename($file);
        }

        $concert = Concert::create([
            'name' => $request->get('name'),
            'date' => $request->get('date'),

            'image' => $name,
            'ticket_order' => $request->get('ticket_order'),
            'canceled' => $request->get('canceled'),
            'no_in_shop' => $request->get('no_in_shop'),
            'hide_concert' => $request->get('hide_concert'),
            'pay_for_organizator' => $request->get('pay_for_organizator'),
            'places' => $request->get('places'),
            'archive' => $request->get('archive'),
            'description' => $request->get('description'),
//            'before' => $request->get('before'),
//            'after' => $request->get('after'),
            'hours' => intval($request->get('hours')),
            'minutes' => intval($request->get('minutes')),
            'dk_id' => intval($request->get('culture')),
            'city_id' => intval($request->get('city')),
            'organizer_id' => intval($request->get('organizer')),
        ]);

        $concert->save();

        $html = view('concerts.concert_row', ['concert' => $concert])->render();

//        return redirect()->route('concerts.index')
//            ->with('success', 'Concert created successfully.');
        return response()->json($html);
    }


    /**
     * Display the specified resource.
     *
     * @param \App\Concert $concert
     * @return \Illuminate\Http\Response
     */
    public function show(Concert $concert)
    {
        return view('concerts.show', compact('concert'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Concert $concert
     * @return \Illuminate\Http\Response
     */
    public function edit(Concert $concert)
    {
        return view('concerts.edit', compact('concert'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Concert $concert
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'date' => 'required',
            'organizer_id' => 'required',
            'city_id' => 'required',
            'dk_id' => 'required',
            'id' => 'required',
        ]);

        $concert = tap(Concert::where('id', $request->get('id')))
            ->update([
                'name' => $request->get('name'),
                'date' => $request->get('date'),
                'organizer_id' => $request->get('organizer_id'),
                'city_id' => $request->get('city_id'),
                'dk_id' => $request->get('dk_id'),
            ])->first();

        $data = [
            'id' => $concert->id,
            'name' => $concert->name,
            'date' => $concert->date,
            'organizer_id' => $concert->organizers->name,
            'city_id' => $concert->cities->city_ru,
            'dk_id' => $concert->cultures->name,
        ];

        return response()->json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Concert $concert
     * @return \Illuminate\Http\Response
     */
    public function destroy(Concert $concert,$id)
    {
        $concert = Concert::find($id);
        $concert->delete();

        return redirect('admin/concerts');
    }

    public function prices($id)
    {
        session()->put('currentConcert', $id);

        $data = Helper::getDkMachineSettings();

        $concert = Concert::findOrFail($id)->with(['colors', 'places'])->get()->first();

        return view('concerts.prices', [
            'settings' => $data['settings'],
            'colors' => $concert->getRelation('colors'),
            'places' => $concert->getRelation('places'),
            'data' => $data['places']
        ]);

    }

    public function getPlaces(Request $request)
    {
        $res = [];
        if ($request->get('places') && $request->get('id')) {
            $id = intval($request->get('id'));
            if ($id) {
                $concert = Concert::findOrFail($id);
                foreach ($concert->places()->get() as $place) {
                    $place->section_id = $place->sections()->first()->slug;
                    $place->price = $place->colors()->first()->price;
                    $place->color = $place->colors()->first()->color;
                    $res[] = $place->toArray();
                }
            }
        }

        return response()->json($res);
    }

    public function savePlaces(Request $request)
    {
        $data = ($request->json())->all();
        $id = session()->get('currentConcert');
        if ($id) {
            $concert = Concert::findOrFail($id);

            foreach ($data['colors'] as $color) {
                $colors = $concert->colors()->updateOrCreate(['color' => $color['color'], 'concert_id' => $id], [
                    'price' => $color['price'],
                    'color' => $color['color'],
                    'count' => $color['count'],
                    'total' => $color['total']
                ]);
            }

            foreach ($data['places'] as $place) {
//                $section_id = Culture::findOrFail($id)->sections()->where('slug', $place['section'])->value('id');
                $section_id = $concert->cultures->sections->where('slug', $place['section'])->first()->id;
                $places = $colors->places()->create([
                    'section_id' => $section_id,
                    'row' => $place['row'],
                    'num_place' => $place['place'],
                    'price' => $colors->price,
                    'concert_id' => $id,
                    'expires' => now()->format('Y-m-d H:i:s')
                ]);
            }
            $places->save();
        }
        return response()->json(['status' => 'ok']);
    }

    public function removeColor(Request $request) {
        $status = 'error';
        $id = $request->get('color_id');
        if($id) {
            Colors::findOrFail($id)->delete();
            $status = 'ok';
        }

        return response()->json(['status' => $status]);
    }

//    public function removeTicket(Request $request) {
//        $params = [];
//        $is_empty = false;
//
//        $concert_id = $request->get('concert');
//        $id = $request->get('id');
//
//        if($request->ajax() && $concert_id && $id) {
//            Cart::removeFromCart($id, $concert_id);
//
//            $place = Places::findOrFail($id)->where([
//                ['concert_id', $concert_id],
//                ['engaged', 1]
//            ])->first();
//
//            $place->engaged = 0;
//            $place->expires = $place->created_at;
//            $place->save();
//
//            $colors = ColorsHelper::getOldColor([$id]);
//            $params['colors'] = $colors;
//
//            if (!Cart::isHasCart()) {
//                $html = view('layouts.order-ticket.cart')->render();
//                $params['html'] = $html;
//                $is_empty = true;
//            } else {
//                $cart = Cart::getCart();
//                $tickets = $cart['tickets'];
//                $places = Places::findOrFail($tickets)->where('concert_id', $concert_id);
//
//                $cart_totals = [
//                    'qty' => count($cart['tickets']),
//                    'total' => $cart['total']
//                ];
//
//
//                $html = view('layouts.order-ticket.cart', [
//                    'concert_id' => $concert_id,
//                    'places' => $places,
//                    'cart_totals' => $cart_totals
//                ])->render();
//
//
////                $colors = [];
////                foreach ($places as $place) {
////                    $place->section_id = $place->sections()->first()->slug;
////                    $place->price = $place->colors()->first()->price;

resources/views/concerts/create.blade.php
@extends('layouts.voyager_admin.voyager_layout')

@section('content')
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">

    <!-- подключаем стили Summernote -->

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.css" rel="stylesheet">
    <link href="{{asset('css/circle-styles.css')}}" rel="stylesheet">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Создать новый концерт</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('concerts.index') }}"> Назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('concerts.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Площадка:</strong>
                    <select name="dk_id" id="dk_id">
                        @foreach($dk as $place)
                            <option value="{{$place->id}}">{{$place->name}}</option>
                            @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Наименование:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name" id="name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Организатор:</strong>
                    <input type="text" name="organizer" class="form-control" placeholder="Организатор" id="organizer">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Дата время:</strong>
                    <input type="datetime-local" name="date" class="form-control" placeholder="Дата" id="date">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Параметры:</strong><br/>
                    <input type="checkbox" name="canceled" value="1" id="canceled">Отменен<br/>
                    <input type="checkbox" name="codes_without_d" value="2" id="codes_without_d">Коды без «D»<br/>
                    <input type="checkbox" name="no_in_shop" value="3" id="no_in_shop">Нет в продаже<br/>
                    <input type="checkbox" name="hide_concert" value="4" id="hide_concert">Скрыть концерт<br/>
                    <input type="checkbox" name="another_codes" value="5" id="another_codes">«Чужие» коды<br/>
                    <input type="checkbox" name="pay_for_organizator" value="6" id="pay_for_organizator">Оплата организатору<br/>
                    <input type="checkbox" name="places" value="7" id="places">Приставные места<br/>
                    <input type="checkbox" name="archive" value="8" id="archive">Архивный<br/>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Фото:</strong>
                    <input type="file" name="image" class="form-control" placeholder="Фото" id="image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <input type="text" name="city" class="form-control" placeholder="Город" id="city">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Описание:</strong>
                    <textarea type="text" id="text" name="description" class="form-control" placeholder="Описание" style="height: 200px;"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Бил-Зак:</strong>
                    <input type="text" name="ticket_order" class="form-control" placeholder="Бил-Зак" readonly value="{{mt_rand()}}" id="ticket_order">
                </div>
            </div>
{{--            <div class="col-xs-12 col-sm-12 col-md-12">--}}
{{--                <div class="form-group">--}}
{{--                    <strong>От:</strong>--}}
{{--                    <input type="number" name="before" class="form-control" placeholder="От">--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="col-xs-12 col-sm-12 col-md-12">--}}
{{--                <div class="form-group">--}}
{{--                    <strong>До:</strong>--}}
{{--                    <input type="number" name="after" class="form-control" placeholder="После">--}}
{{--                </div>--}}
{{--            </div>--}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Часы:</strong>
                    <input type="number" name="hours" class="form-control" placeholder="Часы" id="hours">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Минуты:</strong>
                    <input type="number" name="minutes" class="form-control" placeholder="Минуты" id="minutes">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Создать</button>
            </div>
        </div>

    </form>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <!-- подключаем bootstrap.js -->

    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

    <!-- подключаем сам summernote -->

    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js"></script>

    <script>

        $(document).ready(function() {

            $('#text').summernote();

        });

    </script>
@endsection

resources/views/concerts/edit.blade.php
@extends('layouts.voyager_admin.voyager_layout')

@section('content')
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">

    <!-- подключаем стили Summernote -->

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.css" rel="stylesheet">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Редактировать концерт</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('concerts.index') }}"> Назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('concerts.update',$concert->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Наименование:</strong>
                    <input type="text" name="name" value="{{ $concert->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Площадка:</strong>
                    <input type="text" name="place" value="{{ $concert->place }}" class="form-control" placeholder="Место">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Организатор:</strong>
                    <input type="text" name="organizer" value="{{ $concert->organizer }}" class="form-control" placeholder="Организатор">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <input type="text" name="city" value="{{ $concert->city }}" class="form-control" placeholder="Город">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Дата время:</strong>
                    <input type="datetime-local" name="date" class="form-control" placeholder="Дата" required>
                </div>
            </div>
{{--            <div class="col-xs-12 col-sm-12 col-md-12">--}}
{{--                <div class="form-group">--}}
{{--                    <strong>Фото:</strong>--}}
{{--                    <input type="file" name="image" class="form-control" placeholder="Фото">--}}
{{--                    <img class="dnk-img" src="{{asset("storage/imagesGoods/". $concert->image)}}">--}}
{{--                </div>--}}
{{--            </div>--}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Описание:</strong>
                    <textarea type="text" name="description" class="form-control" placeholder="Описание" style="height: 200px;" id="text">{{ $concert->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>От:</strong>
                    <input type="number" name="before" value="{{ $concert->before }}" class="form-control" placeholder="От">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>До:</strong>
                    <input type="number" name="after" value="{{ $concert->after }}" class="form-control" placeholder="До">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Часы:</strong>
                    <input type="number" name="hours" value="{{ $concert->hours }}" class="form-control" placeholder="Часы">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Минуты:</strong>
                    <input type="number" name="minutes" value="{{ $concert->minutes }}" class="form-control" placeholder="Минуты">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>

    </form>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <!-- подключаем bootstrap.js -->

    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

    <!-- подключаем сам summernote -->

    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js"></script>

    <script>

        $(document).ready(function() {

            $('#text').summernote();

        });

    </script>
@endsection

resources/views/concerts/show.blade.php
@extends('layouts.voyager_admin.voyager_layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Концерт</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('concerts.index') }}"> Назад</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Код:</strong>
                {{ $concert->id }}
            </div>
            <div class="form-group">
                <strong>Название:</strong>
                {{ $concert->name }}
            </div>
            <div class="form-group">
                <strong>Дата:</strong>
                {{ $concert->date }}
            </div>
            <div class="form-group">
                <strong>Фото:</strong>
                <img src="{{ asset('storage/imagesGoods/'.$concert->image) }}" alt="">
            </div>
            <div class="form-group">
                <strong>Организатор:</strong>
                {{ $concert->organizer }}
            </div>
            <div class="form-group">
                <strong>Статус:</strong>
                {{ $concert->status }}
            </div>
            <div class="form-group">
                <strong>Город:</strong>
                {{ $concert->city }}
            </div>
            <div class="form-group">
                <strong>Место:</strong>
                {{ $concert->place }}
            </div>
            <div class="form-group">
                <strong>Бил-Зак:</strong>
                {{ $concert->ticket_order }}
            </div>
            <div class="form-group">
                <strong>Описание:</strong>
                {!! $concert->description !!}
            </div>
            <div class="form-group">
                <strong>От:</strong>
                {{ $concert->before }}
            </div>
            <div class="form-group">
                <strong>До:</strong>
                {{ $concert->after }}
            </div>
            <div class="form-group">
                <strong>Часы:</strong>
                {{ $concert->hours }}
            </div>
            <div class="form-group">
                <strong>Минуты:</strong>
                {{ $concert->minutes }}
            </div>
        </div>
    </div>
@endsection