routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::match(['get','post'], '/', 'HomeController@index')->name('index');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/cashier', 'HomeController@cashier')->name('cashier');

Route::group(['prefix' => 'admin'], function () {
//    Voyager::routes();
    Route::resource('/concerts','ConcertController')->middleware('admin');
    Route::post('/concerts/store','ConcertController@store')->name('concert_create')->middleware('admin');
    Route::post('/concerts/destroy/{id}','ConcertController@destroy')->name('concert_destroy')->middleware('admin');
    Route::post('/concerts/update','ConcertController@update')->name('concert_update')->middleware('admin');
    Route::resource('cities','CityController')->middleware('admin');
    Route::post('/cities/store','CityController@store')->name('city_store')->middleware('admin');
    Route::post('/cities/destroy/{id}','CityController@destroy')->name('city_destroy')->middleware('admin');
    Route::post('/cities/update','CityController@update')->name('city_update')->middleware('admin');
    Route::resource('addresses','AddressController')->middleware('admin');
    Route::post('/addresses/update','AddressController@update')->name('address_update')->middleware('admin');
    Route::post('/addresses/store','AddressController@store')->name('address_store')->middleware('admin');
    Route::post('/addresses/destroy/{id}','AddressController@destroy')->name('address_destroy')->middleware('admin');
    Route::get('/files','FileController@files')->name('files')->middleware('admin');
    Route::get('/payments','PaymentController@payments')->name('payments')->middleware('admin');
    Route::get('/users/create','AdminController@create_user')->name('users_create')->middleware('admin');
    Route::post('/users/store','AdminController@store_user')->name('users_store')->middleware('admin');
//    Route::get('/users/edit/{id}','AdminController@edit_user')->name('users_edit')->middleware('admin');
    Route::post('/users/update','AdminController@update_user')->name('users_update')->middleware('admin');
    Route::post('/users/destroy/{id}','AdminController@destroy_user')->name('users_destroy')->middleware('admin');
    Route::get('/users','AdminController@users')->name('users')->middleware('admin');

});

Route::get('/create_eticket','ETicketController@create')->name('create')->middleware('admin');
Route::post('/store_eticket','ETicketController@store')->name('store_ticket')->middleware('admin');
Route::get('edit_eticket/{id}','ETicketController@edit')->name('ticket_edit')->middleware('admin');
Route::put('update_eticket/{id}','ETicketController@update')->name('ticket_update')->middleware('admin');
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);

    return redirect()->back();
})->name('locale');



Route::get('prices/{id}', 'ConcertController@prices')->name('prices');
Route::post('savePlaces', 'ConcertController@savePlaces')->name('savePlaces');
Route::post('getPlaces', 'ConcertController@getPlaces')->name('getPlaces');

Route::post('removeColor', 'ConcertController@removeColor')->name('removeColor');
Route::post('/removeTicket', 'CartController@removeTicket')->name('removeTicket');

Route::post('reservePlace', 'CartController@reservePlace')->name('reservePlace');
Route::post('clearCart', 'CartController@clearCart')->name('clearCart');
Route::post('processingStatus','CartController@status')->name('processingStatus');

Route::get('calculations/{id}', 'HomeController@calculations')->name('calculations');
Route::get('statistics/{id}', 'HomeController@statistics')->name('statistics');
Route::get('sales/{id}', 'HomeController@sales')->name('sales');
Route::get('report/{id}', 'HomeController@report')->name('report');
Route::get('scene/{id}', 'ConcertScene@order_ticket')->name('order-ticket');
//Route::get('ticket', 'HomeController@ticket')->name('ticket');

Route::get('ticket','ETicketController@index')->name('tickets');
Route::get('concert/{id}', 'HomeController@concert_id')->name('concert-id');

// Payment
//Route::get('checkout/{id}','CheckoutController@index')->name('checkout_id');
Route::get('invoice/{id}','CheckoutController@index')->name('invoice');
Route::match(['get','post'], '/checkout','CheckoutController@checkout')->name('checkout');
Route::post('payment','CheckoutController@payment')->name('payment');
//

Route::get('about','HomeController@about')->name('about');
Route::get('contacts','HomeController@contacts')->name('contacts');



//Route::get('/admin','AdminController@index')->name('admin');
//Route::get('dnk/admin','AdminController@login')->name('dnk_admin');

Route::get('/admin/orders','AdminController@orders')->name('orders')->middleware('admin');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = [
        'city_ru','city_uk','city_en',
    ];

    public function addresses()
    {
        return $this->hasMany(Address::class);
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::latest()->paginate(5);

        return view('cities.index',['cities' => $cities])
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'city_ru' => 'required',
            'city_uk' => 'required',
            'city_en' => 'required',
        ]);

        $city = City::create([
            'city_ru' => $request->get('city_ru'),
            'city_uk' => $request->get('city_uk'),
            'city_en' => $request->get('city_en'),
        ]);

        $city->save();
        $html = view('cities.city_row', ['city' => $city])->render();
        return response()->json($html);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        return view('cities.show',compact('city'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        return view('cities.edit',compact('city'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate([
            'city_ru' => 'required',
            'city_uk' => 'required',
            'city_en' => 'required',
            'id' => 'required',
        ]);

        $city = tap(City::where('id', $request->get('id')))
            ->update([
                'city_ru' => $request->get('city_ru'),
                'city_uk' => $request->get('city_uk'),
                'city_en' => $request->get('city_en'),
            ])->first();

        $data = [
            'id' => $city->id,
            'city_ru' => $city->city_ru,
            'city_uk' => $city->city_uk,
            'city_en' => $city->city_en,

        ];

        return response()->json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $city = City::find($id);
        $city->delete();

        return redirect('admin/cities');
    }
}

resources/views/cities/city_row.blade.php
@if(!empty($city))
    <tr class="table-row" data-city="{{$city->id}}">
        <td data-td="id" data-value="{{ $city->id }}" class="city-id-table">{{ $city->id }}</td>
        <td data-td="city_ru" data-value="{{ $city->city_ru }}">{{ $city->city_ru }}</td>
        <td data-td="city_uk" data-value="{{ $city->city_uk }}">{{ $city->city_uk }}</td>
        <td data-td="city_en" data-value="{{ $city->city_en }}">{{ $city->city_en }}</td>
        <td class="admin_actions">
            <div class="dropdown">
                <button class="btn btn-default" id="dropdownMenu" type="button" data-toggle="dropdown"
                        aria-expanded="false">
                    <b>Управление</b> <img src="{{asset('img/arrow-up.svg')}}" alt=""> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                    <li role="presentation"><img src="{{asset('img/edit.svg')}}" alt="">
                        <button class="btn edit-city" data-toggle="modal" data-target="#cityEditModal" data-id="{{$city->id}}">
                            Редактировать
                        </button>
                    </li>
                    <form action="{{ route('city_destroy',$city->id) }}" method="POST">
                        @csrf
                        <li role="presentation"><img src="{{asset('img/delete.svg')}}" alt="">
                            <button type="submit" class="btn">
                                Удалить
                            </button>
                        </li>
                    </form>
                </ul>
            </div>
        </td>
    </tr>
@endif

resources/views/cities/create.blade.php
@extends('cities.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Добавить город</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cities.index') }}"> назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('cities.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город(ru):</strong>
                    <input type="text" name="city_ru" class="form-control" placeholder="Город">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город(ua):</strong>
                    <input type="text" name="city_uk" class="form-control" placeholder="Місто">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город(en):</strong>
                    <input type="text" name="city_en" class="form-control" placeholder="City">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/cities/edit.blade.php
@extends('cities.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Редактировать</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cities.index') }}"> назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('cities.update',$city->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <input type="text" name="city" value="{{ $city->city }}" class="form-control" placeholder="Город">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>

    </form>
@endsection

resources/views/cities/index.blade.php
@extends('layouts.voyager_admin.voyager_layout')


@section('page_title')
    <p>Города</p>
@endsection

@section('button_options')
    <div class="btn-group">
        <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            <img src="{{asset('img/admin-concerts.png')}}" alt="">
        </button>
        <div class="dropdown-menu">
            <div class="col-12">
                <img src="{{asset('img/add.svg')}}" alt="">
                <button type="button" class="btn" data-toggle="modal" data-target="#concertModal">Новый</button>
            </div>
            <div class="col-12">
                <img src="{{asset('img/statistics.svg')}}" alt="">
                <button type="button" class="btn">
                    Отчет
                </button>
            </div>
            <div class="col-12">
                <img src="{{asset('img/import.svg')}}" alt="">
                <button type="button" class="btn">
                    Импорт
                </button>
            </div>
            <div class="col-12">
                <img src="{{asset('img/sale.svg')}}" alt="">
                <button type="button" class="btn">
                    Продажи
                </button>
            </div>
        </div>
    </div>
@endsection


@section('page_subtitle')
    <span>Список городов</span>
@endsection

@section('table')
    <table class="table table-bordered" id="cities">
        <tr class="tr-1">
            <th class="tr-1-th-1">#</th>
            <th>Город(ru)</th>
            <th>Город(ua)</th>
            <th>Город(en)</th>
            <th width="280px">Действие</th>
        </tr>
        @foreach ($cities as $city)
            @include('cities.city_row')
        @endforeach
    </table>
@endsection

@section('modal')
    <div class="modal fade" id="concertModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content admin-user-modal-content">
                <div class="modal-header">
                    Город
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="city_create_form">
                    <div class="modal-body">
                        <div class="row">
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(ru)</label>
                                        <input type="text" name="city_ru"
                                               class="form-control fw-input-admin qa-phone-field"
                                               required></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(ua)</label>
                                        <input type="text" name="city_uk"
                                               class="form-control fw-input-admin qa-phone-field"
                                               required></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(en)</label>
                                        <input type="text" name="city_en"
                                               class="form-control fw-input-admin qa-phone-field"
                                               required></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary admin_cancel_concert" data-dismiss="modal"><img
                                    src="{{asset('img/delete.svg')}}" alt="">Отмена
                        </button>
                        <button type="submit" class="btn admin_create_concert"><img
                                    src="{{asset('img/admin_create_concert.svg')}}" alt="">Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="cityEditModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content admin-user-modal-content">
                <div class="modal-header">
                    Город
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="city_edit_form">
                    <div class="modal-body">
                        <div class="row">
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error fw-focused">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(ru)</label>
                                        <input type="text" name="city_ru" id="city_ru"
                                               class="form-control fw-input-admin qa-phone-field city-ru-edit"
                                               required value=""></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error fw-focused">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(ua)</label>
                                        <input type="text" name="city_uk" id="city_uk"
                                               class="form-control fw-input-admin qa-phone-field city-ua-edit"
                                               required value=""></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                            <div class="fw-field-container-admin qa-fw-field-container b-auth-last-form-field fw-field-container--has-span">
                                <div class="fw-field fw-has-error qa-fw-has-error fw-focused">
                                    <div class="fw-field__content add_concert_admin">
                                        <label for="name">Город(en)</label>
                                        <input type="text" name="city_en" id="city_en"
                                               class="form-control fw-input-admin qa-phone-field city-en-edit"
                                               required value=""></div>
                                </div>
                                <span class="fw-field__error qa-fw-field__error"></span>
                            </div>
                            <input type="hidden" name="id" id="id">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary admin_cancel_concert" data-dismiss="modal"><img
                                    src="{{asset('img/delete.svg')}}" alt="">Отмена
                        </button>
                        <button type="submit" class="btn admin_create_concert" id="city_edit"><img
                                    src="{{asset('img/admin_create_concert.svg')}}" alt="">Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
{{--    <script src="{{asset('js/admin/voyager.js')}}" defer></script>--}}
<script type="module" src="{{asset('js/admin/cities/cities.js')}}" defer></script>
@endsection

resources/views/cities/show.blade.php
@extends('cities.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cities.index') }}"> Назад</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Город:</strong>
                {{ $city->city }}
            </div>
        </div>
    </div>
@endsection