routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::match(['get','post'], '/', 'HomeController@index')->name('index');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/cashier', 'HomeController@cashier')->name('cashier');

Route::group(['prefix' => 'admin'], function () {
//    Voyager::routes();
    Route::resource('/concerts','ConcertController')->middleware('admin');
    Route::post('/concerts/store','ConcertController@store')->name('concert_create')->middleware('admin');
    Route::post('/concerts/destroy/{id}','ConcertController@destroy')->name('concert_destroy')->middleware('admin');
    Route::post('/concerts/update','ConcertController@update')->name('concert_update')->middleware('admin');
    Route::resource('cities','CityController')->middleware('admin');
    Route::post('/cities/store','CityController@store')->name('city_store')->middleware('admin');
    Route::post('/cities/destroy/{id}','CityController@destroy')->name('city_destroy')->middleware('admin');
    Route::post('/cities/update','CityController@update')->name('city_update')->middleware('admin');
    Route::resource('addresses','AddressController')->middleware('admin');
    Route::post('/addresses/update','AddressController@update')->name('address_update')->middleware('admin');
    Route::post('/addresses/store','AddressController@store')->name('address_store')->middleware('admin');
    Route::post('/addresses/destroy/{id}','AddressController@destroy')->name('address_destroy')->middleware('admin');
    Route::get('/files','FileController@files')->name('files')->middleware('admin');
    Route::get('/payments','PaymentController@payments')->name('payments')->middleware('admin');
    Route::get('/users/create','AdminController@create_user')->name('users_create')->middleware('admin');
    Route::post('/users/store','AdminController@store_user')->name('users_store')->middleware('admin');
//    Route::get('/users/edit/{id}','AdminController@edit_user')->name('users_edit')->middleware('admin');
    Route::post('/users/update','AdminController@update_user')->name('users_update')->middleware('admin');
    Route::post('/users/destroy/{id}','AdminController@destroy_user')->name('users_destroy')->middleware('admin');
    Route::get('/users','AdminController@users')->name('users')->middleware('admin');

});

Route::get('/create_eticket','ETicketController@create')->name('create')->middleware('admin');
Route::post('/store_eticket','ETicketController@store')->name('store_ticket')->middleware('admin');
Route::get('edit_eticket/{id}','ETicketController@edit')->name('ticket_edit')->middleware('admin');
Route::put('update_eticket/{id}','ETicketController@update')->name('ticket_update')->middleware('admin');
Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);

    return redirect()->back();
})->name('locale');



Route::get('prices/{id}', 'ConcertController@prices')->name('prices');
Route::post('savePlaces', 'ConcertController@savePlaces')->name('savePlaces');
Route::post('getPlaces', 'ConcertController@getPlaces')->name('getPlaces');

Route::post('removeColor', 'ConcertController@removeColor')->name('removeColor');
Route::post('/removeTicket', 'CartController@removeTicket')->name('removeTicket');

Route::post('reservePlace', 'CartController@reservePlace')->name('reservePlace');
Route::post('clearCart', 'CartController@clearCart')->name('clearCart');
Route::post('processingStatus','CartController@status')->name('processingStatus');

Route::get('calculations/{id}', 'HomeController@calculations')->name('calculations');
Route::get('statistics/{id}', 'HomeController@statistics')->name('statistics');
Route::get('sales/{id}', 'HomeController@sales')->name('sales');
Route::get('report/{id}', 'HomeController@report')->name('report');
Route::get('scene/{id}', 'ConcertScene@order_ticket')->name('order-ticket');
//Route::get('ticket', 'HomeController@ticket')->name('ticket');

Route::get('ticket','ETicketController@index')->name('tickets');
Route::get('concert/{id}', 'HomeController@concert_id')->name('concert-id');

// Payment
//Route::get('checkout/{id}','CheckoutController@index')->name('checkout_id');
Route::get('invoice/{id}','CheckoutController@index')->name('invoice');
Route::match(['get','post'], '/checkout','CheckoutController@checkout')->name('checkout');
Route::post('payment','CheckoutController@payment')->name('payment');
//

Route::get('about','HomeController@about')->name('about');
Route::get('contacts','HomeController@contacts')->name('contacts');



//Route::get('/admin','AdminController@index')->name('admin');
//Route::get('dnk/admin','AdminController@login')->name('dnk_admin');

Route::get('/admin/orders','AdminController@orders')->name('orders')->middleware('admin');

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\City;
use App\Concert;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::all();
        $addresses = Address::latest()->paginate(5);

        return view('addresses.index',['addresses' => $addresses,'cities' => $cities])
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('addresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'city_id' => 'required',
            'address_ru' => 'required',
            'text_ru' => 'required',
            'address_uk' => 'required',
            'text_ua' => 'required',
            'address_en' => 'required',
            'text_en' => 'required',
        ]);

        $address = Address::create([
            'city_id' => $request->get('city_id'),
            'address_ru' => $request->get('address_ru'),
            'text_ru' => $request->get('text_ru'),
            'address_uk' => $request->get('address_uk'),
            'text_ua' => $request->get('text_ua'),
            'address_en' => $request->get('address_en'),
            'text_en' => $request->get('text_en'),
        ]);

        $address->save();

        $html = view('addresses.address_row', ['address' => $address])->render();

        return response()->json($html);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function show(Address $address)
    {
        return view('addresses.show',compact('address'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function edit(Address $address)
    {
        return view('addresses.edit',compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate([
            'address_ru' => 'required',
            'text_ru' => 'required',
            'address_uk' => 'required',
            'text_ua' => 'required',
            'address_en' => 'required',
            'text_en' => 'required',
            'id' => 'required',
        ]);

        $address = tap(Address::where('id', $request->get('id')))
            ->update([
                'address_ru' => $request->get('address_ru'),
                'text_ru' => $request->get('text_ru'),
                'address_uk' => $request->get('address_uk'),
                'text_ua' => $request->get('text_ua'),
                'address_en' => $request->get('address_en'),
                'text_en' => $request->get('text_en'),
            ])->first();

        $data = [
            'id' => $address->id,
            'address_ru' => $address->address_ru,
            'text_ru' => $address->text_ru,
            'address_uk' => $address->address_uk,
            'text_ua' => $address->text_ua,
            'address_en' => $address->address_en,
            'text_en' => $address->text_en,

        ];

        return response()->json($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Address  $address
     * @return \Illuminate\Http\Response
     */
    public function destroy(Address $address,$id)
    {
        $address = Address::find($id);
        $address->delete();

        return redirect('admin/addresses');
    }
}

resources/views/addresses/address_row.blade.php
@if(!empty($address))
    <tr class="table-row" data-city="{{$address->id}}">
        <td class="tr-1-th-1">{{ $address->id }}</td>
        <td data-td="address_ru" data-value="{{ $address->address_ru }}">{{ $address->address_ru }}</td>
        <td data-td="text_ru" data-value="{{ $address->text_ru }}">{!! $address->text_ru !!}</td>
        <td data-td="address_uk" data-value="{{ $address->address_uk }}">{{ $address->address_uk }}</td>
        <td data-td="text_ua" data-value="{{ $address->text_ua }}">{!! $address->text_ua !!}</td>
        <td data-td="address_en" data-value="{{ $address->address_en }}">{{ $address->address_en }}</td>
        <td data-td="text_en" data-value="{{ $address->text_en }}">{!! $address->text_en !!}</td>
        <td data-td="id" data-value="{{ $address->id }}" class="city-id-table">{{ $address->cities->city_ru }}</td>
        <td class="admin_actions">
            <div class="dropdown">
                <button class="btn btn-default" id="dropdownMenu" type="button" data-toggle="dropdown"
                        aria-expanded="false">
                    <b>Управление</b> <img src="{{asset('img/arrow-up.svg')}}" alt=""> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                    <li role="presentation"><img src="{{asset('img/edit.svg')}}" alt="">
                        <button class="btn edit-address" data-toggle="modal" data-target="#addressEditModal" data-id="{{$address->id}}">
                            Редактировать
                        </button>
                    </li>
                    <form action="{{route('address_destroy',$address->id)}}" method="POST">
                        @csrf
                        <li role="presentation"><img src="{{asset('img/delete.svg')}}" alt="">
                            <button type="submit" class="btn">
                                Удалить
                            </button>
                        </li>
                    </form>
                </ul>
            </div>
        </td>
    </tr>
@endif

resources/views/addresses/create.blade.php
@extends('addresses.layout')

@section('content')
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">

    <!-- подключаем стили Summernote -->

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.css" rel="stylesheet">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Добавить адресс</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('addresses.index') }}"> назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('addresses.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <span>Адресс(ru)</span>
                <div class="form-group">
                    <strong>Адресс:</strong>
                    <input type="text" name="address_ru" class="form-control" placeholder="Адрес">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Текст:</strong>
                    <textarea type="text" name="text_ru" id="address_ru" class="form-control" placeholder="Текст"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <select name="city_id">
                        <?php $cities = DB::table('cities')->get();?>
                        @foreach($cities as $city)
                        <option name="city_id" value="{{$city->id}}">{{$city->id}}-{{$city->city_ru}}</option>
                            @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <span>Адресс(ua)</span>
                <div class="form-group">
                    <strong>Адресс:</strong>
                    <input type="text" name="address_ua" class="form-control" placeholder="Адрес">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Текст:</strong>
                    <textarea type="text" name="text_ua" id="address_ua" class="form-control" placeholder="Текст"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <select name="city_id">
                        <?php $cities = DB::table('cities')->get();?>
                        @foreach($cities as $city)
                            <option name="city_id" value="{{$city->id}}">{{$city->id}}-{{$city->city_ru}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <span>Адресс(en)</span>
                <div class="form-group">
                    <strong>Адресс:</strong>
                    <input type="text" name="address_en" class="form-control" placeholder="Адрес">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Текст:</strong>
                    <textarea type="text" name="text_en" id="address_en" class="form-control" placeholder="Текст"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <select name="city_id">
                        <?php $cities = DB::table('cities')->get();?>
                        @foreach($cities as $city)
                            <option name="city_id" value="{{$city->id}}">{{$city->id}}-{{$city->city_ru}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <!-- подключаем bootstrap.js -->

    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

    <!-- подключаем сам summernote -->

    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js"></script>

    <script>

        $(document).ready(function() {

            $('#address_ru').summernote();
            $('#address_ua').summernote();
            $('#address_en').summernote();

        });

    </script>
@endsection

resources/views/addresses/edit.blade.php
@extends('addresses.layout')

@section('content')
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">

    <!-- подключаем стили Summernote -->

    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.css" rel="stylesheet">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Редактировать</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('addresses.index') }}"> назад</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('addresses.update',$address->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Адрес:</strong>
                    <input type="text" name="address" value="{{ $address->address }}" class="form-control" placeholder="Адрес">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>С:</strong>
                    <input type="number" name="start" value="{{ $address->start }}" class="form-control" placeholder="С">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>До:</strong>
                    <input type="number" name="finish" value="{{ $address->finish }}" class="form-control" placeholder="До">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Текст:</strong>
                    <textarea type="text" name="text" id="text" class="form-control" placeholder="Текст">{{ $address->text }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Телефон:</strong>
                    <input type="number" name="phone" value="{{ $address->phone }}" class="form-control" placeholder="Телефон">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Город:</strong>
                    <input type="text" name="city_id" value="{{ $address->city_id }}" class="form-control" placeholder="Город">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>

    </form>

    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <!-- подключаем bootstrap.js -->

    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>

    <!-- подключаем сам summernote -->

    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.7/summernote.js"></script>

    <script>

        $(document).ready(function() {

            $('#text').summernote();

        });

    </script>
@endsection

resources/views/addresses/show.blade.php
@extends('addresses.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('addresses.index') }}"> Назад</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Адрес:</strong>
                {{ $address->address }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>С:</strong>
                {{ $address->start }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>До:</strong>
                {{ $address->finish }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Текст:</strong>
                {{ $address->text }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Телефон:</strong>
                {{ $address->phone }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Город:</strong>
                {{ $address->city_id }}
            </div>
        </div>
    </div>
@endsection